
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov 18 2025 20:54:00 CST (Nov 19 2025 02:54:00 UTC)

// Verification Directory fv/mac 
`timescale 1ns/1ps
module mac(clk, rstb, IN, W, OUT);
  input clk, rstb;
  input [3:0] IN, W;
  output [11:0] OUT;
  wire clk, rstb;
  wire [3:0] IN, W;
  wire [11:0] OUT;
  wire [11:0] acc_reg;
  wire [7:0] mult_reg;
  wire [3:0] cycle_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_122;
  SDFFR_X1 \OUT_reg[11] (.RN (rstb), .CK (clk), .D (n_109), .SE
       (n_111), .SI (OUT[11]), .Q (OUT[11]), .QN (UNCONNECTED));
  DFFR_X1 \acc_reg_reg[11] (.RN (rstb), .CK (clk), .D (n_110), .Q
       (acc_reg[11]), .QN (UNCONNECTED0));
  SDFFR_X1 \OUT_reg[10] (.RN (rstb), .CK (clk), .D (n_107), .SE
       (n_111), .SI (OUT[10]), .Q (OUT[10]), .QN (UNCONNECTED1));
  DFFR_X1 \acc_reg_reg[10] (.RN (rstb), .CK (clk), .D (n_108), .Q
       (acc_reg[10]), .QN (UNCONNECTED2));
  SDFFR_X1 \OUT_reg[9] (.RN (rstb), .CK (clk), .D (n_105), .SE (n_111),
       .SI (OUT[9]), .Q (OUT[9]), .QN (UNCONNECTED3));
  AND2_X1 g2218__8780(.A1 (n_109), .A2 (n_111), .ZN (n_110));
  DFFR_X1 \acc_reg_reg[9] (.RN (rstb), .CK (clk), .D (n_106), .Q
       (acc_reg[9]), .QN (n_0));
  AND2_X1 g2222__4296(.A1 (n_107), .A2 (n_111), .ZN (n_108));
  AND2_X1 g2220__3772(.A1 (n_105), .A2 (n_111), .ZN (n_106));
  XNOR2_X1 g2223__1474(.A (n_102), .B (n_82), .ZN (n_109));
  SDFFR_X1 \OUT_reg[8] (.RN (rstb), .CK (clk), .D (n_103), .SE (n_111),
       .SI (OUT[8]), .Q (OUT[8]), .QN (UNCONNECTED4));
  XNOR2_X1 g2226__4547(.A (n_101), .B (n_83), .ZN (n_107));
  DFFR_X1 \acc_reg_reg[8] (.RN (rstb), .CK (clk), .D (n_104), .Q
       (acc_reg[8]), .QN (UNCONNECTED5));
  XNOR2_X1 g2225__9682(.A (n_98), .B (n_86), .ZN (n_105));
  AND2_X1 g2228__2683(.A1 (n_103), .A2 (n_111), .ZN (n_104));
  OAI211_X1 g2229__1309(.A (n_77), .B (n_99), .C1 (n_100), .C2 (n_76),
       .ZN (n_102));
  NAND2_X1 g2231__6877(.A1 (n_100), .A2 (n_99), .ZN (n_101));
  DFFR_X1 \acc_reg_reg[7] (.RN (rstb), .CK (clk), .D (n_96), .Q
       (acc_reg[7]), .QN (UNCONNECTED6));
  SDFFR_X1 \OUT_reg[7] (.RN (rstb), .CK (clk), .D (n_95), .SE (n_111),
       .SI (OUT[7]), .Q (OUT[7]), .QN (UNCONNECTED7));
  AOI21_X1 g2232__2900(.A (n_81), .B1 (n_97), .B2 (n_94), .ZN (n_98));
  XNOR2_X1 g2233__2391(.A (n_97), .B (n_84), .ZN (n_103));
  AND2_X1 g2234__7675(.A1 (n_95), .A2 (n_111), .ZN (n_96));
  NAND3_X1 g2235__7118(.A1 (n_97), .A2 (n_87), .A3 (n_94), .ZN (n_100));
  FA_X1 g2236__8757(.A (acc_reg[7]), .B (mult_reg[7]), .CI (n_91), .CO
       (n_97), .S (n_95));
  SDFFR_X1 \OUT_reg[6] (.RN (rstb), .CK (clk), .D (n_92), .SE (n_111),
       .SI (OUT[6]), .Q (OUT[6]), .QN (UNCONNECTED8));
  DFFR_X1 \acc_reg_reg[6] (.RN (rstb), .CK (clk), .D (n_93), .Q
       (acc_reg[6]), .QN (UNCONNECTED9));
  AND2_X1 g2239__1786(.A1 (n_92), .A2 (n_111), .ZN (n_93));
  FA_X1 g2240__5953(.A (acc_reg[6]), .B (mult_reg[6]), .CI (n_88), .CO
       (n_91), .S (n_92));
  SDFFR_X1 \OUT_reg[5] (.RN (rstb), .CK (clk), .D (n_89), .SE (n_111),
       .SI (OUT[5]), .Q (OUT[5]), .QN (UNCONNECTED10));
  DFFR_X1 \acc_reg_reg[5] (.RN (rstb), .CK (clk), .D (n_90), .Q
       (acc_reg[5]), .QN (UNCONNECTED11));
  AND2_X1 g2243__5703(.A1 (n_89), .A2 (n_111), .ZN (n_90));
  FA_X1 g2244__7114(.A (acc_reg[5]), .B (mult_reg[5]), .CI (n_74), .CO
       (n_88), .S (n_89));
  INV_X1 g2246(.A (n_85), .ZN (n_87));
  HA_X1 g2247__5266(.A (n_0), .B (n_75), .CO (n_85), .S (n_86));
  NAND2_X1 g2249__2250(.A1 (n_80), .A2 (n_94), .ZN (n_84));
  DFFR_X1 \acc_reg_reg[4] (.RN (rstb), .CK (clk), .D (n_79), .Q
       (acc_reg[4]), .QN (UNCONNECTED12));
  SDFFR_X1 \OUT_reg[4] (.RN (rstb), .CK (clk), .D (n_78), .SE (n_111),
       .SI (OUT[4]), .Q (OUT[4]), .QN (UNCONNECTED13));
  XNOR2_X1 g2250__6083(.A (acc_reg[10]), .B (mult_reg[7]), .ZN (n_83));
  XNOR2_X1 g2252__2703(.A (acc_reg[11]), .B (mult_reg[7]), .ZN (n_82));
  INV_X1 g2253(.A (n_80), .ZN (n_81));
  AND2_X1 g2251__5795(.A1 (n_111), .A2 (n_78), .ZN (n_79));
  NAND2_X1 g2256__7344(.A1 (acc_reg[8]), .A2 (mult_reg[7]), .ZN (n_80));
  OR2_X1 g2257__1840(.A1 (acc_reg[8]), .A2 (mult_reg[7]), .ZN (n_94));
  NAND2_X1 g2258__5019(.A1 (acc_reg[10]), .A2 (mult_reg[7]), .ZN
       (n_77));
  NOR2_X1 g2259__1857(.A1 (acc_reg[10]), .A2 (mult_reg[7]), .ZN (n_76));
  OAI21_X1 g2260__9906(.A (mult_reg[7]), .B1 (acc_reg[9]), .B2
       (acc_reg[8]), .ZN (n_99));
  FA_X1 g2254__8780(.A (acc_reg[4]), .B (mult_reg[4]), .CI (n_67), .CO
       (n_74), .S (n_78));
  DFFR_X1 \mult_reg_reg[7] (.RN (rstb), .CK (clk), .D (n_73), .Q
       (mult_reg[7]), .QN (n_75));
  DFFR_X1 \mult_reg_reg[6] (.RN (rstb), .CK (clk), .D (n_71), .Q
       (mult_reg[6]), .QN (UNCONNECTED14));
  SDFFR_X1 \OUT_reg[3] (.RN (rstb), .CK (clk), .D (n_68), .SE (n_111),
       .SI (OUT[3]), .Q (OUT[3]), .QN (UNCONNECTED15));
  DFFR_X1 \acc_reg_reg[3] (.RN (rstb), .CK (clk), .D (n_69), .Q
       (acc_reg[3]), .QN (UNCONNECTED16));
  INV_X1 g2266(.A (n_72), .ZN (n_73));
  OAI21_X1 g2267__4296(.A (n_52), .B1 (n_70), .B2 (n_57), .ZN (n_72));
  XNOR2_X1 g2268__3772(.A (n_70), .B (n_58), .ZN (n_71));
  AND2_X1 g2265__1474(.A1 (n_111), .A2 (n_68), .ZN (n_69));
  DFFR_X1 \mult_reg_reg[5] (.RN (rstb), .CK (clk), .D (n_66), .Q
       (mult_reg[5]), .QN (UNCONNECTED17));
  FA_X1 g2269__4547(.A (acc_reg[3]), .B (mult_reg[3]), .CI (n_61), .CO
       (n_67), .S (n_68));
  XNOR2_X1 g2273__9682(.A (n_65), .B (n_56), .ZN (n_66));
  OAI21_X1 g2274__2683(.A (n_55), .B1 (n_65), .B2 (n_54), .ZN (n_70));
  DFFR_X1 \mult_reg_reg[4] (.RN (rstb), .CK (clk), .D (n_64), .Q
       (mult_reg[4]), .QN (UNCONNECTED18));
  DFFR_X1 \acc_reg_reg[2] (.RN (rstb), .CK (clk), .D (n_63), .Q
       (acc_reg[2]), .QN (UNCONNECTED19));
  SDFFR_X1 \OUT_reg[2] (.RN (rstb), .CK (clk), .D (n_62), .SE (n_111),
       .SI (OUT[2]), .Q (OUT[2]), .QN (UNCONNECTED20));
  FA_X1 g2278__1309(.A (n_47), .B (n_44), .CI (n_59), .CO (n_65), .S
       (n_64));
  AND2_X1 g2276__6877(.A1 (n_111), .A2 (n_62), .ZN (n_63));
  FA_X1 g2277__2900(.A (acc_reg[2]), .B (mult_reg[2]), .CI (n_48), .CO
       (n_61), .S (n_62));
  DFFR_X1 \mult_reg_reg[3] (.RN (rstb), .CK (clk), .D (n_60), .Q
       (mult_reg[3]), .QN (UNCONNECTED21));
  FA_X1 g2280__2391(.A (n_43), .B (n_27), .CI (n_45), .CO (n_59), .S
       (n_60));
  SDFFR_X1 \OUT_reg[1] (.RN (rstb), .CK (clk), .D (n_50), .SE (n_111),
       .SI (OUT[1]), .Q (OUT[1]), .QN (UNCONNECTED22));
  DFFR_X1 \acc_reg_reg[1] (.RN (rstb), .CK (clk), .D (n_51), .Q (n_3),
       .QN (acc_reg[1]));
  NOR2_X1 g2288__7675(.A1 (n_57), .A2 (n_53), .ZN (n_58));
  XNOR2_X1 g2282__7118(.A (n_55), .B (n_54), .ZN (n_56));
  INV_X1 g2292(.A (n_52), .ZN (n_53));
  AND2_X1 g2286__8757(.A1 (n_111), .A2 (n_50), .ZN (n_51));
  NOR2_X1 g2293__1786(.A1 (n_49), .A2 (W[3]), .ZN (n_57));
  DFFR_X1 \mult_reg_reg[2] (.RN (rstb), .CK (clk), .D (n_46), .Q
       (mult_reg[2]), .QN (UNCONNECTED23));
  NAND3_X1 g2294__5953(.A1 (n_49), .A2 (IN[3]), .A3 (W[3]), .ZN (n_52));
  FA_X1 g2287__5703(.A (n_3), .B (mult_reg[1]), .CI (n_35), .CO (n_48),
       .S (n_50));
  FA_X1 g2284__7114(.A (n_25), .B (n_13), .CI (n_33), .CO (n_54), .S
       (n_47));
  FA_X1 g2296__5266(.A (n_8), .B (n_5), .CI (n_32), .CO (n_49), .S
       (n_55));
  DFFR_X1 \cycle_count_reg[3] (.RN (rstb), .CK (clk), .D (n_41), .Q
       (cycle_count[3]), .QN (UNCONNECTED24));
  XOR2_X1 g2289__2250(.A (n_40), .B (n_42), .Z (n_46));
  FA_X1 g2297__6083(.A (n_14), .B (n_11), .CI (n_26), .CO (n_44), .S
       (n_45));
  OR2_X1 g2295__2703(.A1 (n_39), .A2 (n_42), .ZN (n_43));
  DFFR_X1 \acc_reg_reg[0] (.RN (rstb), .CK (clk), .D (n_38), .Q (n_2),
       .QN (acc_reg[0]));
  SDFFR_X1 \OUT_reg[0] (.RN (rstb), .CK (clk), .D (n_37), .SE (n_111),
       .SI (OUT[0]), .Q (OUT[0]), .QN (UNCONNECTED25));
  NOR2_X1 g2300__5795(.A1 (n_36), .A2 (n_30), .ZN (n_41));
  HA_X1 g2298__7344(.A (n_28), .B (n_17), .CO (n_39), .S (n_40));
  DFFR_X1 \cycle_count_reg[2] (.RN (rstb), .CK (clk), .D (n_34), .Q
       (cycle_count[2]), .QN (n_1));
  AND2_X1 g2302__1840(.A1 (n_111), .A2 (n_37), .ZN (n_38));
  DFFR_X1 \cycle_count_reg[0] (.RN (rstb), .CK (clk), .D (n_31), .Q
       (cycle_count[0]), .QN (UNCONNECTED26));
  XNOR2_X1 g2303__5019(.A (n_23), .B (cycle_count[3]), .ZN (n_36));
  DFFR_X1 \cycle_count_reg[1] (.RN (rstb), .CK (clk), .D (n_122), .Q
       (cycle_count[1]), .QN (UNCONNECTED27));
  HA_X1 g2304__1857(.A (n_2), .B (mult_reg[0]), .CO (n_35), .S (n_37));
  AND2_X1 g2305__9906(.A1 (n_24), .A2 (n_111), .ZN (n_34));
  DFFR_X1 \mult_reg_reg[1] (.RN (rstb), .CK (clk), .D (n_19), .Q
       (mult_reg[1]), .QN (UNCONNECTED28));
  INV_X1 g2306(.A (n_21), .ZN (n_33));
  INV_X1 g2307(.A (n_20), .ZN (n_32));
  NOR2_X1 g2315__8780(.A1 (n_30), .A2 (cycle_count[0]), .ZN (n_31));
  HA_X1 g2309__3772(.A (n_7), .B (n_6), .CO (n_27), .S (n_28));
  HA_X1 g2310__1474(.A (n_4), .B (n_10), .CO (n_25), .S (n_26));
  HA_X1 g2311__4547(.A (n_22), .B (cycle_count[2]), .CO (n_23), .S
       (n_24));
  HA_X1 g2308__9682(.A (n_12), .B (n_9), .CO (n_20), .S (n_21));
  NOR2_X1 g2316__2683(.A1 (n_42), .A2 (n_15), .ZN (n_19));
  INV_X1 g2320(.A (n_111), .ZN (n_30));
  NAND3_X1 g2322__1309(.A1 (n_18), .A2 (cycle_count[3]), .A3 (n_1), .ZN
       (n_111));
  DFFR_X1 \mult_reg_reg[0] (.RN (rstb), .CK (clk), .D (n_16), .Q
       (mult_reg[0]), .QN (UNCONNECTED29));
  AND2_X1 g2319__6877(.A1 (n_17), .A2 (n_16), .ZN (n_42));
  AOI22_X1 g2321__2900(.A1 (IN[1]), .A2 (W[0]), .B1 (IN[0]), .B2
       (W[1]), .ZN (n_15));
  AND2_X1 g2337__2391(.A1 (IN[1]), .A2 (W[2]), .ZN (n_14));
  NAND2_X1 g2328__7675(.A1 (IN[1]), .A2 (W[3]), .ZN (n_13));
  AND2_X1 g2331__7118(.A1 (IN[3]), .A2 (W[1]), .ZN (n_12));
  NAND2_X1 g2336__8757(.A1 (IN[0]), .A2 (W[3]), .ZN (n_11));
  NOR2_X1 g2332__1786(.A1 (cycle_count[1]), .A2 (cycle_count[0]), .ZN
       (n_18));
  AND2_X1 g2334__5953(.A1 (cycle_count[1]), .A2 (cycle_count[0]), .ZN
       (n_22));
  AND2_X1 g2330__5703(.A1 (IN[0]), .A2 (W[0]), .ZN (n_16));
  NAND2_X1 g2325__7114(.A1 (IN[3]), .A2 (W[0]), .ZN (n_10));
  NAND2_X1 g2323__5266(.A1 (IN[2]), .A2 (W[2]), .ZN (n_9));
  NAND2_X1 g2329__2250(.A1 (IN[3]), .A2 (W[2]), .ZN (n_8));
  AND2_X1 g2335__6083(.A1 (IN[2]), .A2 (W[0]), .ZN (n_7));
  AND2_X1 g2326__2703(.A1 (IN[0]), .A2 (W[2]), .ZN (n_6));
  NAND2_X1 g2327__5795(.A1 (IN[2]), .A2 (W[3]), .ZN (n_5));
  AND2_X1 g2324__7344(.A1 (IN[2]), .A2 (W[1]), .ZN (n_4));
  AND2_X1 g2333__1840(.A1 (IN[1]), .A2 (W[1]), .ZN (n_17));
  NOR2_X1 g2(.A1 (n_18), .A2 (n_22), .ZN (n_122));
endmodule

